q = input("Enter your question: ")
print("You entered:", q)

num1= ("45")
num2= str(55)
sum = num1+num2
print(type(num1))
print(type(num2))
print(sum)

name = input("what is your name? ")
age = input("what is your age? ")
print("Hello " + name + ", you are " + age + " years old.")

# write a escape sequence character in python 
print("Hello \"World\"")
print("Hello \'World\'")
print("Hello \\World\\")
print("Hello \nWorld")
print("Hello \tWorld")
print("Hello \bWorld")
print("Hello \fWorld")
print("Hello \rWorld")
print("Hello \vWorld")
print("Hello \oooWorld")
print("Hello \x41World")
print("Hello \u0041World")
print("Hello \U0001F600World")
print("Hello \N{grinning face}World")
print("Hello \aWorld")
print("Hello \cWorld")
print("Hello \eWorld")
print("Hello \0World")
print("Hello \x00World")
print("Hello \u0000World")
print("Hello \U00000000World")
